repos:
  - repo: local
    hooks:
    -   id: format
        name: format
        entry: npm run format
        language: unsupported
        always_run: true
        pass_filenames: false

    -   id: build
        name: build
        entry: npm run build
        language: unsupported
        always_run: true
        pass_filenames: false
